version = "3.11.1"

maxColumn = 140
trailingCommas = "always"

align.preset = more

indent.caseSite = 2
indent.defnSite = 2

runner.dialect = scala3
continuationIndent.defnSite = 2
continuationIndent.extendSite = 2

newlines.beforeTypeBounds = unfold

rewrite.rules = [Imports, SortModifiers]
rewrite.imports.expand = true
rewrite.imports.sort = scalastyle
